/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Brand — teal / navy educational palette (no purple cluster)
        teal: {
          50: '#F0FDFA',
          100: '#CCFBF1',
          200: '#99F6E4',
          300: '#5EEAD4',
          400: '#2DD4BF',
          500: '#14B8A6',
          600: '#0D9488',
          700: '#0F766E',
          800: '#115E59',
          900: '#134E4A',
        },
        navy: {
          50: '#F0F4F8',
          100: '#D9E2EC',
          200: '#BCCCDC',
          300: '#9FB3C8',
          400: '#829AB1',
          500: '#627D98',
          600: '#486581',
          700: '#334E68',
          800: '#243B53',
          900: '#102A43',
        },
        // Semantic (light defaults; pair with dark: variants in components)
        background: {
          DEFAULT: '#F8FAFC',
          secondary: '#F1F5F9',
          dark: '#102A43',
          'dark-secondary': '#243B53',
        },
        surface: {
          DEFAULT: '#FFFFFF',
          elevated: '#FFFFFF',
          dark: '#243B53',
          'dark-elevated': '#334E68',
        },
        foreground: {
          DEFAULT: '#102A43',
          muted: '#486581',
          inverse: '#F8FAFC',
          dark: '#F0F4F8',
          'dark-muted': '#9FB3C8',
        },
        border: {
          DEFAULT: '#D9E2EC',
          strong: '#9FB3C8',
          dark: '#486581',
          'dark-strong': '#627D98',
        },
        primary: {
          DEFAULT: '#0D9488',
          foreground: '#FFFFFF',
          muted: '#CCFBF1',
          dark: '#2DD4BF',
          'dark-foreground': '#102A43',
          'dark-muted': '#115E59',
        },
        secondary: {
          DEFAULT: '#243B53',
          foreground: '#F8FAFC',
          dark: '#CCFBF1',
          'dark-foreground': '#102A43',
        },
        success: {
          DEFAULT: '#059669',
          foreground: '#FFFFFF',
          dark: '#34D399',
          'dark-foreground': '#102A43',
        },
        warning: {
          DEFAULT: '#D97706',
          foreground: '#FFFFFF',
          dark: '#FBBF24',
          'dark-foreground': '#102A43',
        },
        danger: {
          DEFAULT: '#DC2626',
          foreground: '#FFFFFF',
          dark: '#F87171',
          'dark-foreground': '#102A43',
        },
        // Chat UX accent (user bubbles) — not brand primary
        'chat-user': {
          DEFAULT: '#4F46E5',
          foreground: '#FFFFFF',
          dark: '#6366F1',
          'dark-foreground': '#FFFFFF',
        },
      },
      fontFamily: {
        sans: ['System'],
        mono: ['monospace'],
      },
      fontSize: {
        xs: ['12px', { lineHeight: '16px' }],
        sm: ['14px', { lineHeight: '20px' }],
        base: ['16px', { lineHeight: '24px' }],
        lg: ['18px', { lineHeight: '28px' }],
        xl: ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '36px' }],
      },
      borderRadius: {
        none: '0px',
        sm: '4px',
        DEFAULT: '8px',
        md: '10px',
        lg: '12px',
        xl: '16px',
        full: '9999px',
      },
      spacing: {
        0.5: '2px',
        1: '4px',
        1.5: '6px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
      },
    },
  },
  plugins: [],
};
